version: '3.7'

services:
  app:
    container_name: portfolio_app
    build:
      context: .
    command: pnpm start:dev
    volumes:
      - .:/app
      - app/node_modules
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - database
  database:
    container_name: portfolio_database
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}