version: '3.3'

services:
  app:
    container_name: portfolio_app
    env_file:
      - .env
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
  database:
    container_name: portfolio_database
    image: postgres:14.1
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}